### ISSUE TITLE
RuntimeError: Bad magic number in .pyc file

### ISSUE THREAD

**Issue by RussiaVk** [wibiti/uncompyle2#59] opened 2019-01-15 09:09 UTC
windowsxpsp3

**Comment by mathieu-aubin** [comment] 2019-04-29 05:35
wrong/bad/broken pyc file - badly compiled, missing the magic bytes (filetype marker bytes). Can't uncompyle a bad file to begin with.

Not much else can be said here and the issue is common for python.

That 'program', in it's original state of purpose (ie for what it was originally intended for), would simply not run, triggering the same error unless being recompiled. To solve this issue, deleting all pyc files usually does the trick but depending on your relation with the source code, you might not have the luxury of recompiling them.

please close this issue or provide more details if you still think this is attributed to this program

**Closed** 2019-04-29 08:33 UTC
